name: Deploy Layout Bundle to CDN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        run: |
          yarn
          yarn build
      - name: upload
        uses: actions/checkout@v2
        uses: bacongobbler/azure-blob-storage-upload@main
        with:
          source_dir: '/'
          container_name: layout
          connection_string: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
          overwrite: 'true'
